
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.alexeav.ru
  resources:
  - namespacecontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.alexeav.ru
  resources:
  - namespacecontrollers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.alexeav.ru
  resources:
  - namespacecontrollers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
