apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-controller
subjects:
- kind: ServiceAccount
  name: namespace-controller-manager
  namespace: namespace-controller
